// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrbiWpPEyrLi-UmZZ_gkJk5vEQIzLodzw',
    appId: '1:455240536437:web:ba1d5f0b5af4175dfc433c',
    messagingSenderId: '455240536437',
    projectId: 'retire1-1a558',
    authDomain: 'retire1-1a558.firebaseapp.com',
    storageBucket: 'retire1-1a558.firebasestorage.app',
    measurementId: 'G-MTFJM0TN1Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzDuO_1T6c_jfrjQK7M-p8M8nF2VNXzhQ',
    appId: '1:455240536437:android:522867207db9b7a1fc433c',
    messagingSenderId: '455240536437',
    projectId: 'retire1-1a558',
    storageBucket: 'retire1-1a558.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHbn40kgUm7UsIyZDqrI8YU4w6BPEGXpg',
    appId: '1:455240536437:ios:b16acfb6d5fa3908fc433c',
    messagingSenderId: '455240536437',
    projectId: 'retire1-1a558',
    storageBucket: 'retire1-1a558.firebasestorage.app',
    iosBundleId: 'dev.turbo2000.retire1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHbn40kgUm7UsIyZDqrI8YU4w6BPEGXpg',
    appId: '1:455240536437:ios:b16acfb6d5fa3908fc433c',
    messagingSenderId: '455240536437',
    projectId: 'retire1-1a558',
    storageBucket: 'retire1-1a558.firebasestorage.app',
    iosBundleId: 'dev.turbo2000.retire1',
  );
}
